// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace StealthTech.RayTracer.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ConesFeature : Xunit.IClassFixture<ConesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Cones.feature"
#line hidden
        
        public ConesFeature(ConesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Cones", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Intersecting a cone with a ray")]
        [Xunit.TraitAttribute("FeatureTitle", "Cones")]
        [Xunit.TraitAttribute("Description", "Intersecting a cone with a ray")]
        [Xunit.InlineDataAttribute("Point(0, 0, -5)", "Vector(0, 0, 1)", "5", "5", new string[0])]
        [Xunit.InlineDataAttribute("Point(0, 0, -5)", "Vector(1, 1, 1)", "8.66025", "8.66025", new string[0])]
        [Xunit.InlineDataAttribute("Point(1, 1, -5)", "Vector(-0.5, -1, 1)", "4.55006", "49.44994", new string[0])]
        public virtual void IntersectingAConeWithARay(string origin, string direction, string t0, string t1, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Intersecting a cone with a ray", null, exampleTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
 testRunner.Given("cone ← Cone()", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.And(string.Format("direction ← {0}.Normalize()", direction), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.And(string.Format("ray ← Ray({0}, direction)", origin), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.When("intersections ← cone.LocalIntersect(ray)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("intersections.Count = 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.And(string.Format("intersections[0].Time = {0}", t0), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("intersections[1].Time = {0}", t1), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Intersecting a cone with a ray parallel to one of its halves")]
        [Xunit.TraitAttribute("FeatureTitle", "Cones")]
        [Xunit.TraitAttribute("Description", "Intersecting a cone with a ray parallel to one of its halves")]
        public virtual void IntersectingAConeWithARayParallelToOneOfItsHalves()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Intersecting a cone with a ray parallel to one of its halves", null, ((string[])(null)));
#line 18
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 19
 testRunner.Given("cone ← Cone()", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.And("direction ← Vector(0, 1, 1).Normalize()", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("ray ← Ray(Point(0, 0, -1), direction)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.When("intersections ← cone.LocalIntersect(ray)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("intersections.Count = 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
 testRunner.And("intersections[0].Time = 0.35355", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Intersecting a cone\'s end caps")]
        [Xunit.TraitAttribute("FeatureTitle", "Cones")]
        [Xunit.TraitAttribute("Description", "Intersecting a cone\'s end caps")]
        [Xunit.InlineDataAttribute("Point(0, 0, -5)", "Vector(0, 1, 0)", "0", new string[0])]
        [Xunit.InlineDataAttribute("Point(0, 0, -0.25)", "Vector(0, 1, 1)", "2", new string[0])]
        [Xunit.InlineDataAttribute("Point(0, 0, -0.25)", "Vector(0, 1, 0)", "4", new string[0])]
        public virtual void IntersectingAConesEndCaps(string origin, string direction, string count, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Intersecting a cone\'s end caps", null, exampleTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 27
 testRunner.Given("cone ← Cone()", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.And("cone.Minimum ← -0.5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("cone.Maximum ← 0.5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("cone.IsClosed ← true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And(string.Format("direction ← {0}.Normalize()", direction), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And(string.Format("ray ← Ray({0}, direction)", origin), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.When("intersections ← cone.LocalIntersect(ray)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
 testRunner.Then(string.Format("intersections.Count = {0}", count), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Computing the normal vector on a capped cone")]
        [Xunit.TraitAttribute("FeatureTitle", "Cones")]
        [Xunit.TraitAttribute("Description", "Computing the normal vector on a capped cone")]
        [Xunit.InlineDataAttribute("Point(0, 0, 0)", "Vector(0, 0, 0)", new string[0])]
        [Xunit.InlineDataAttribute("Point(1, 1, 1)", "Vector(1, -√2, 1)", new string[0])]
        [Xunit.InlineDataAttribute("Point(-1, -1, 0)", "Vector(-1, 1, 0)", new string[0])]
        public virtual void ComputingTheNormalVectorOnACappedCone(string point, string normal, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Computing the normal vector on a capped cone", null, exampleTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 43
 testRunner.Given("cone ← Cone()", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 44
 testRunner.When(string.Format("normalVector ← cone.LocalNormalAt({0})", point), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then(string.Format("normalVector = {0}", normal), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Computing the normal vector on a cone")]
        [Xunit.TraitAttribute("FeatureTitle", "Cones")]
        [Xunit.TraitAttribute("Description", "Computing the normal vector on a cone")]
        [Xunit.InlineDataAttribute("Point(0, 1, 0)", "Vector(0, -1, 0)", new string[0])]
        [Xunit.InlineDataAttribute("Point(0, 2, 0)", "Vector(0, 1, 0)", new string[0])]
        [Xunit.InlineDataAttribute("Point(0.5, 2, 0)", "Vector(0, 1, 0)", new string[0])]
        public virtual void ComputingTheNormalVectorOnACone(string point, string normal, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Computing the normal vector on a cone", null, exampleTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 54
 testRunner.Given("cone ← Cone()", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 55
 testRunner.And("cone.Minimum ← 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("cone.Maximum ← 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("cone.IsClosed ← true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.When(string.Format("normalVector ← cone.LocalNormalAt({0})", point), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.Then(string.Format("normalVector = {0}", normal), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ConesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ConesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
